package entitys;
// Generated 25/10/2019 05:16:54 AM by Hibernate Tools 4.3.1



/**
 * Alumno generated by hbm2java
 */
public class Alumno  implements java.io.Serializable {


     private int idUsuario;
     private Grupo grupo;
     private Usuario usuario;
     private String rutaXmlrespuestas;

    public Alumno() {
    }

	
    public Alumno(Grupo grupo, Usuario usuario) {
        this.grupo = grupo;
        this.usuario = usuario;
    }
    public Alumno(Grupo grupo, Usuario usuario, String rutaXmlrespuestas) {
       this.grupo = grupo;
       this.usuario = usuario;
       this.rutaXmlrespuestas = rutaXmlrespuestas;
    }
   
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Grupo getGrupo() {
        return this.grupo;
    }
    
    public void setGrupo(Grupo grupo) {
        this.grupo = grupo;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getRutaXmlrespuestas() {
        return this.rutaXmlrespuestas;
    }
    
    public void setRutaXmlrespuestas(String rutaXmlrespuestas) {
        this.rutaXmlrespuestas = rutaXmlrespuestas;
    }




}


