package entitys;
// Generated 11/11/2019 08:09:09 PM by Hibernate Tools 4.3.1



/**
 * Alumno generated by hbm2java
 */
public class Alumno  implements java.io.Serializable {


     private Integer idUsuario;
     private Grupo grupo;
     private Usuario usuario;
     private String rutaXmlrespuestas;

    public Alumno() {
    }

	
    public Alumno(Usuario usuario) {
        this.usuario = usuario;
    }
    public Alumno(Grupo grupo, Usuario usuario, String rutaXmlrespuestas) {
       this.grupo = grupo;
       this.usuario = usuario;
       this.rutaXmlrespuestas = rutaXmlrespuestas;
    }
    
    public Alumno(Grupo grupo, String rutaXmlrespuestas) {
       this.grupo = grupo;
       this.rutaXmlrespuestas = rutaXmlrespuestas;
    }
   
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Grupo getGrupo() {
        return this.grupo;
    }
    
    public void setGrupo(Grupo grupo) {
        this.grupo = grupo;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getRutaXmlrespuestas() {
        return this.rutaXmlrespuestas;
    }
    
    public void setRutaXmlrespuestas(String rutaXmlrespuestas) {
        this.rutaXmlrespuestas = rutaXmlrespuestas;
    }




}


