package entitys;
// Generated 25/10/2019 05:16:54 AM by Hibernate Tools 4.3.1



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer idUsuario;
     private Tipousuario tipousuario;
     private String nombres;
     private String apellidoPat;
     private String apellidoMat;
     private String nombreUsuario;
     private String contrasena;

    public Usuario() {
    }

    public Usuario(Tipousuario tipousuario, String nombres, String apellidoPat, String apellidoMat, String nombreUsuario, String contrasena) {
       this.tipousuario = tipousuario;
       this.nombres = nombres;
       this.apellidoPat = apellidoPat;
       this.apellidoMat = apellidoMat;
       this.nombreUsuario = nombreUsuario;
       this.contrasena = contrasena;
    }
   
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Tipousuario getTipousuario() {
        return this.tipousuario;
    }
    
    public void setTipousuario(Tipousuario tipousuario) {
        this.tipousuario = tipousuario;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApellidoPat() {
        return this.apellidoPat;
    }
    
    public void setApellidoPat(String apellidoPat) {
        this.apellidoPat = apellidoPat;
    }
    public String getApellidoMat() {
        return this.apellidoMat;
    }
    
    public void setApellidoMat(String apellidoMat) {
        this.apellidoMat = apellidoMat;
    }
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }




}


